# Generated by Django 4.1 on 2022-09-01 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_models',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('re_enter_password', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField()),
                ('interest_rate_followed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='customer_models',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='')),
                ('area_code', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='areas_models',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=200)),
                ('area_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finb.customer_models')),
            ],
        ),
        migrations.CreateModel(
            name='accounts_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lone_amount', models.FloatField()),
                ('lone_issue_date', models.DateTimeField(auto_now_add=True)),
                ('daily_debt', models.IntegerField()),
                ('number_of_days', models.IntegerField()),
                ('paid_amount', models.FloatField(default=0)),
                ('debt_amount', models.FloatField()),
                ('interest', models.IntegerField(default=0)),
                ('is_debt_closed', models.BooleanField(default=False)),
                ('area_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finb.areas_models')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finb.customer_models')),
            ],
        ),
    ]
