# Generated by Django 4.1 on 2022-09-06 07:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts_models',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, validators=[django.core.validators.RegexValidator('[9876][0-9]{9}$')])),
                ('lone_amount', models.FloatField()),
                ('lone_issue_date', models.DateTimeField(auto_now_add=True)),
                ('daily_debt', models.IntegerField()),
                ('number_of_days', models.IntegerField()),
                ('paid_amount', models.FloatField(default=0)),
                ('debt_amount', models.FloatField()),
                ('interest', models.IntegerField(default=0)),
                ('is_debt_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='areas_models',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area_code', models.CharField(max_length=50, unique=True)),
                ('area_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='company_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(max_length=100)),
                ('re_enter_password', models.CharField(max_length=100)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, validators=[django.core.validators.RegexValidator('[9876][0-9]{9}$')])),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('interest_rate_followed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer_models',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='')),
                ('customer_address', models.TextField()),
                ('area_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finb.areas_models')),
                ('mobile_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finb.accounts_models')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finb.accounts_models')),
            ],
        ),
        migrations.AddField(
            model_name='accounts_models',
            name='area_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finb.areas_models'),
        ),
    ]
