# Generated by Django 4.1 on 2022-09-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas_models',
            name='area_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
