# Generated by Django 4.1 on 2022-09-07 06:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('finb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_models',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
