# Generated by Django 4.1 on 2022-09-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finb', '0002_alter_company_models_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas_models',
            name='area_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
