# Generated by Django 4.1 on 2022-09-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finb', '0002_alter_areas_models_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_models',
            name='area_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finb.areas_models'),
        ),
    ]
