# Generated by Django 4.1 on 2022-09-02 15:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('finb', '0003_alter_customer_models_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_models',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company_models',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
