# Generated by Django 4.1 on 2022-09-02 15:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('finb', '0004_alter_accounts_models_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_models',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
