# Generated by Django 4.1 on 2022-09-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finb', '0005_customer_models_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_models',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
